---
- name: Firewall change means Enable firewall service
  hosts: all
  become: yes


  tasks:
  - name: Enable a service in firewalld
    firewalld:
      #service: nginx
      port: 80/tcp
      permanent: true
      state: enabled   #disebled


  - name: Reload the firewalld
    service: 
      name: firewalld
      state: reloaded
      
